### ISSUE TITLE
Windows ARM build bustage with xxHash 0.8.1

### ISSUE THREAD

**Issue by rvandermeulen** [Cyan4973/xxHash#620]
Hi, I'm trying to update Firefox' copy of xxHash from version 0.8.0 to 0.8.1 and our Windows ARM builds are failing with the below error and others along the same line:
`INFO -  /builds/worker/checkouts/gecko/mfbt/lz4/xxhash.h(4039,9): error: unknown type name 'uint64x2_t'; did you mean 'uint64_t'?`

Looks like it's missing the arm_neon.h include needed for that type?

**Comment by rvandermeulen** [comment]
Looks like a regression from #598 (@easyaspi314). I can confirm that the below patch fixes the issue without causing issues for ARM builds on other platforms:
```
diff --git a/mfbt/lz4/xxhash.h b/mfbt/lz4/xxhash.h
--- a/mfbt/lz4/xxhash.h
+++ b/mfbt/lz4/xxhash.h
@@ -4024,16 +4024,18 @@ XXH_FORCE_INLINE XXH_TARGET_SSE2 void XX
             dst16[i] = _mm_add_epi64(_mm_load_si128((const __m128i *)src16+i), seed);
     }   }
 }
 
 #endif
 
 #if (XXH_VECTOR == XXH_NEON)
 
+#include <arm_neon.h>
+
 XXH_FORCE_INLINE void
 XXH3_accumulate_512_neon( void* XXH_RESTRICT acc,
                     const void* XXH_RESTRICT input,
                     const void* XXH_RESTRICT secret)
 {
     XXH_ASSERT((((size_t)acc) & 15) == 0);
     {
         uint64x2_t* const xacc = (uint64x2_t *) acc;
```

**Comment by easyaspi314** [comment]
[Try this](https://github.com/easyaspi314/xxHash/tree/msvc_arm_hotfix)

It should also detect ARM64EC on VS2022 preview and fix `ARMv__ARM_ARCH` in the cli for 32-bit builds.

**Comment by rvandermeulen** [comment]
AFAIK, arm_neon.h detects and includes arm64_neon.h if needed (and arm64_neon.h doesn't include all the definitions that arm_neon.h does), so I think you can unconditionally just use arm_neon.h.

**Comment by easyaspi314** [comment]
This doesn't seem to be the case for some earlier versions of MSVC 2017, where it would error saying it was only for ARM targets. Microsoft always has to keep it interesting. 😅

**Comment by rvandermeulen** [comment]
Yeah, trying to include arm64_neon.h directly leads to linker errors like the below (this is with MSVC 15.9.6, fwiw):
`lld-link: error: undefined symbol: neon_ld1m_q8` (we use clang-cl/lld-link in our build environment)

If I change your patch to the below, the builds are successful:
```
#  if defined(_M_ARM64) || defined(_M_ARM64EC) || defined(_M_ARM_ARMV7VE)
#    include <arm_neon.h>
#  endif
```

I can only test the xxhash.h changes, unfortunately. We don't utilize the cli code in Firefox.

**Comment by rvandermeulen** [comment]
https://developercommunity.visualstudio.com/t/arm-neonh-doenst-support-arm64-compiler/201662 was the upstream issue which fixed the bug you mentioned. It says it was fixed in 16.2, but they must have backported it to 15.x at some point as noted above.

**Comment by rvandermeulen** [comment]
Welp, I'm officially confused now. I've been able to confirm that the version of arm_neon.h we use in our build infrastructure matches the official one from MSVC 15.9 with the `#error This header is specific to ARM targets` line in it. With that being the case, I have no idea why including arm_neon.h is working but arm64_neon.h isn't 😞

**Comment by rvandermeulen** [comment]
But I guess on your end, you can condition things on _MSC_VER >= 1922 as the release where things were supposed to start working.

**Comment by Cyan4973** [comment]
Do I understand this `ARM` build issue is specific to `MSVC` ?
And specific to some versions of `MSVC` ?

I'm surprised it wasn't detected in CI, but maybe it's so specific that it only happens beyond the list of platforms currently tested. One of the remaining questions will be : should we extend CI to cover this case too ?

**Comment by easyaspi314** [comment]
What exact version of cl.exe (not visual studio) do you have? I can't reproduce either bug on the latest VS2017 build tools (19.16.27045).

**Comment by rvandermeulen** [comment]
We're using clang 13 (clang-cl more specifically). Our builds still require MSVC for the headers primarily but most of the heavy lifting is clang.

**Comment by easyaspi314** [comment]
That would've been nice to know beforehand before I frantically searched Visual Studio's release notes for any changes on that. 🥲

In that case, the fix is easy.

**Comment by rvandermeulen** [comment]
Sorry for the confusion around that. I'm happy to say that your latest fix appears to work perfectly across all of the platforms/configs we build on 😄.
![image](https://user-images.githubusercontent.com/3661247/144114784-fecbd8c7-8d1c-4bff-814a-ed1f80046efe.png)
